export ZSH="/home/tzhang/.oh-my-zsh"

ZSH_THEME="xiong-chiamiov-zt"

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias vi=vim
alias large="cd /data/tzhang"

export PATH=/home/tzhang/soft/vim81/bin:$PATH



# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/tzhang/soft/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/tzhang/soft/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/tzhang/soft/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/tzhang/soft/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

